Repository DataDog/extendeddaemonset, pull requests merged in 2020-09, with the labels that each got.

#31 update release process like operator
  .github/workflows/pr-linter.yml
  .github/workflows/release.yaml
  Makefile
  RELEASING.md
  chart/extendeddaemonset/Chart.yaml
  deploy/olm-catalog/csv-config.yaml
  deploy/olm-catalog/extendeddaemonset/0.1.0/datadoghq.com_extendeddaemonsetreplicasets_crd.yaml
  deploy/olm-catalog/extendeddaemonset/0.1.0/datadoghq.com_extendeddaemonsets_crd.yaml
  deploy/olm-catalog/extendeddaemonset/0.1.0/datadoghq.com_extendeddaemonsetsettings_crd.yaml
  deploy/olm-catalog/extendeddaemonset/0.1.0/extendeddaemonset.clusterserviceversion.yaml
  deploy/olm-catalog/extendeddaemonset/extendeddaemonset.package.yaml
  hack/generate-olm-bundle.sh
  hack/pre-release.sh
  hack/release/eds-plugin-tmpl.yaml
  hack/release/generate-chart-tarball.sh
  hack/release/generate-plugin-manifest.sh
Labels: enhancement

#32 add missing files for release
  hack/os-env.sh
  hack/pre-release.sh
  hack/release/cluster-service-version-patch.yaml
Labels: bug

#34 fix symlink in the chart
  chart/extendeddaemonset/templates/datadoghq.com_extendeddaemonsetreplicasets_crd.yaml
  chart/extendeddaemonset/templates/datadoghq.com_extendeddaemonsets_crd.yaml
Labels: bug, component/chart

#35 [CI] Add Dockerhub jobs
  .gitlab-ci.yml
Labels: enhancement

#38 Push the EDS plugin on the GitHub release page instead of the controller
  .goreleaser.yml
  hack/release/eds-plugin-tmpl.yaml
  hack/release/generate-plugin-manifest.sh
Labels: bug

#40 Add ignoreEvictedPods config
  pkg/controller/extendeddaemonsetreplicaset/filters.go
  pkg/controller/extendeddaemonsetreplicaset/filters_test.go
Labels: enhancement

#41 Fix exclude nodes feature
  README.md
  examples/foo-eds_exclude-node.yaml
  pkg/controller/extendeddaemonset/extendeddaemonset_controller.go
  pkg/controller/utils/affinity/affinity.go
  pkg/controller/utils/affinity/affinity_test.go
Labels: bug, documentation

#42 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement
