Repository DataDog/extendeddaemonset, pull requests merged in 2020-11, with the labels that each got.

#51 add parameter to configure max restarts for canary pause
  README.md
  api/v1alpha1/extendeddaemonset_default.go
  api/v1alpha1/extendeddaemonset_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_extendeddaemonsets.yaml
  config/crd/bases/v1beta1/datadoghq.com_extendeddaemonsets.yaml
  controllers/extendeddaemonset/controller.go
  controllers/extendeddaemonsetreplicaset/strategy/canary.go
  examples/foo-eds_v2.yaml
  examples/kind-cluster-configuration.yaml
  pkg/controller/test/new.go
  pkg/controller/utils/pod/pod.go
  pkg/controller/utils/pod/pod_test.go
  pkg/plugin/canary.go
  pkg/plugin/validate.go
Labels: enhancement

#50 Add eds_controller_leader gauge to identify leader from /metrics and /ksmetrics
  README.md
  go.mod
  main.go
  pkg/controller/metrics/leader.go
  pkg/controller/metrics/register.go
Labels: enhancement

#56 Add canary paused / failed metrics
  controllers/extendeddaemonset/metrics.go
Labels: enhancement

#57 [e2e] Validate the canary properly in e2e tests
  controllers/extendeddaemonset_test.go
Labels: bug, component/controller

#59 Fix push_release_tag_* jobs in release CI
  .gitlab-ci.yml
Labels: bug

#61 fix canary fail metric
  controllers/extendeddaemonset/metrics.go
Labels: bug

#62 remove alpha version text
  README.md
Labels: documentation

#63 Merge V0.4 release branch
  .gitlab-ci.yml
  bundle/manifests/datadoghq.com_extendeddaemonsets.yaml
  bundle/manifests/extendeddaemonset.clusterserviceversion.yaml
  controllers/extendeddaemonset/metrics.go
Labels: component/chart, component/controller, enhancement

#64 Update release instructions
  RELEASING.md
Labels: documentation

#65 Fix spec.strategy.ReconcileFrequency defaulting check
  api/v1alpha1/extendeddaemonset_default.go
Labels: bug

#66 Add ERS canary NoRestartDuration and AutoFail configuration options to complement AutoPause behavior
  LICENSE-3rdparty.csv
  api/v1alpha1/const.go
  api/v1alpha1/extendeddaemonset_default.go
  api/v1alpha1/extendeddaemonset_types.go
  api/v1alpha1/extendeddaemonset_validate.go
  api/v1alpha1/extendeddaemonset_validate_test.go
  api/v1alpha1/extendeddaemonsetreplicaset_types.go
  api/v1alpha1/utils.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_extendeddaemonsets.yaml
  config/crd/bases/v1beta1/datadoghq.com_extendeddaemonsets.yaml
  controllers/extendeddaemonset/controller.go
  controllers/extendeddaemonset/utils.go
  controllers/extendeddaemonset/utils_test.go
  controllers/extendeddaemonsetreplicaset/controller.go
  controllers/extendeddaemonsetreplicaset/strategy/canary.go
  controllers/extendeddaemonsetreplicaset/strategy/canary_test.go
  controllers/extendeddaemonsetreplicaset/strategy/rollingupdate.go
  controllers/extendeddaemonsetreplicaset/strategy/type.go
  controllers/extendeddaemonsetreplicaset/strategy/utils.go
  controllers/extendeddaemonsetreplicaset/strategy/utils_test.go
  examples/foo-eds_v3_restarts.yaml
  examples/kind-cluster-configuration.yaml
  go.mod
  go.sum
  pkg/controller/utils/pod/pod.go
  pkg/controller/utils/pod/pod_test.go
Labels: component/controller, enhancement
