Repository DataDog/extendeddaemonset, pull requests merged in 2021-07, with the labels that each got.

#103 Bump Kind version
  .github/workflows/validation.yml
Labels: bug

#102 Fix eds check threshold calculation
  cmd/check-eds/upgrade/upgrade.go
Labels: component/controller, enhancement

#104 [CI] Switch to helm/kind GH action
  .github/workflows/validation.yml
Labels: component/controller, enhancement

#105 [CI] Add kube versions matrix
  .github/workflows/validation.yml
Labels: component/controller, enhancement

#106 Do not overwrite the canary duration
  .github/workflows/validation.yml
  api/v1alpha1/extendeddaemonset_default.go
Labels: bug, component/controller
