Repository DataDog/extendeddaemonset, pull requests merged in 2021-08, with the labels that each got.

#108 Adapt metadata validation patch for CRD v1
  config/crd/bases/v1/datadoghq.com_extendeddaemonsetreplicasets.yaml
  config/crd/bases/v1/datadoghq.com_extendeddaemonsets.yaml
  hack/patch-crd-metadata.yaml
  hack/patch-crds.sh
Labels: bug

#109 Delete Helm chart
  README.md
  chart/extendeddaemonset/.helmignore
  chart/extendeddaemonset/Chart.yaml
  chart/extendeddaemonset/crds/datadoghq.com_extendeddaemonsetreplicasets.yaml
  chart/extendeddaemonset/crds/datadoghq.com_extendeddaemonsets.yaml
  chart/extendeddaemonset/crds/datadoghq.com_extendeddaemonsetsettings.yaml
  chart/extendeddaemonset/templates/NOTES.txt
  chart/extendeddaemonset/templates/_helpers.tpl
  chart/extendeddaemonset/templates/clusterrole.yaml
  chart/extendeddaemonset/templates/clusterrole_binding.yaml
  chart/extendeddaemonset/templates/deployment.yaml
  chart/extendeddaemonset/templates/role.yaml
  chart/extendeddaemonset/templates/role_binding.yaml
  chart/extendeddaemonset/templates/serviceaccount.yaml
  chart/extendeddaemonset/values.yaml
Labels: enhancement

#111 [eds_validate test] Use correct spec in "valid autoPause no autoFail" test
  api/v1alpha1/extendeddaemonset_validate_test.go
Labels: bug

#112 Fix "up-to-date" value reported in EDS status
  controllers/extendeddaemonset/controller.go
  controllers/extendeddaemonset/controller_test.go
Labels: bug, component/controller

#110 Generate a PodTemplate for each EDS
  api/v1alpha1/test/new.go
  config/rbac/role.yaml
  controllers/podtemplate/controller.go
  controllers/podtemplate/controller_test.go
  controllers/podtemplate/doc.go
  controllers/podtemplate_controller.go
  controllers/setup.go
Labels: enhancement, component/controller

#107 Automate EDS Krew plugin releasing
  .github/workflows/release.yaml
Labels: enhancement

#114 Fix release.yaml
  .github/workflows/release.yaml
Labels: bug

#115 add ers strategy tests
  controllers/extendeddaemonsetreplicaset/controller.go
  controllers/extendeddaemonsetreplicaset/strategy/canary.go
  controllers/extendeddaemonsetreplicaset/strategy/canary_test.go
  controllers/extendeddaemonsetreplicaset/strategy/rollingupdate.go
  controllers/extendeddaemonsetreplicaset/strategy/rollingupdate_test.go
  controllers/extendeddaemonsetreplicaset/strategy/unknown.go
  controllers/extendeddaemonsetreplicaset/strategy/utils_test.go
Labels: enhancement

#101 Use number of unschedulable/undeletable PODs in limits computation. Avoid blocking EDS rollout due to nodes in NotReady state
  controllers/extendeddaemonsetreplicaset/strategy/canary_test.go
  controllers/extendeddaemonsetreplicaset/strategy/limits/limits.go
  controllers/extendeddaemonsetreplicaset/strategy/rollingupdate.go
  controllers/extendeddaemonsetreplicaset/strategy/rollingupdate_test.go
  controllers/extendeddaemonsetreplicaset/strategy/unknown.go
Labels: enhancement

#116 add tests in pkg/controller/utils
  pkg/controller/utils/affinity/affinity_test.go
  pkg/controller/utils/comparison/comparison_test.go
  pkg/controller/utils/labels_test.go
  pkg/controller/utils/list_test.go
  pkg/controller/utils/pod/create_test.go
  pkg/controller/utils/pod/pod_test.go
Labels: enhancement

#117 [README] Fix reference to the `kubectl-eds` make target
  README.md
Labels: documentation

#119 Fix kubebuild download URL
  hack/install-kubebuilder.sh
Labels: bug

#120 Fix kubebuild download URL (#119)
  hack/install-kubebuilder.sh
Labels: bug

#118 fix condition for github action release
  .github/workflows/release.yaml
Labels: bug

#121 [Release] v0.7.0-rc.2
  bundle/manifests/extendeddaemonset.clusterserviceversion.yaml
Labels: enhancement

#122 [github actions] Delete "generate chart tarball" job
  .github/workflows/release.yaml
  hack/release/generate-chart-tarball.sh
Labels: bug

#123 [release] v0.7.0-rc.3
  bundle/manifests/extendeddaemonset.clusterserviceversion.yaml
Labels: enhancement
