Repository DataDog/extendeddaemonset, pull requests merged in 2021-06, with the labels that each got.

#97 [Plugin] Compile with CGO enabled
  Makefile
Labels: component/plugin, enhancement

#98 Add completion pct target to eds-check
  cmd/check-eds/upgrade/upgrade.go
Labels: enhancement

#99 added validationMode param with configurable default
  README.md
  api/v1alpha1/extendeddaemonset_default.go
  api/v1alpha1/extendeddaemonset_types.go
  api/v1alpha1/extendeddaemonset_validate.go
  api/v1alpha1/extendeddaemonset_validate_test.go
  api/v1alpha1/zz_generated.openapi.go
  bundle/manifests/datadoghq.com_extendeddaemonsets.yaml
  chart/extendeddaemonset/templates/deployment.yaml
  chart/extendeddaemonset/values.yaml
  config/crd/bases/v1/datadoghq.com_extendeddaemonsets.yaml
  config/crd/bases/v1beta1/datadoghq.com_extendeddaemonsets.yaml
  controllers/extendeddaemonset/controller.go
  controllers/extendeddaemonset/controller_test.go
  controllers/extendeddaemonset_e2e_test.go
  controllers/extendeddaemonsetreplicaset/controller_test.go
  controllers/setup.go
  controllers/suite_test.go
  main.go
  pkg/config/config.go
Labels: component/controller, enhancement
