Repository DataDog/extendeddaemonset, pull requests merged in 2021-01, with the labels that each got.

#75 [Plugin] Fix commands in help output
  pkg/plugin/get/get.go
  pkg/plugin/get/geters.go
  pkg/plugin/pods/pods.go
Labels: bug, component/plugin

#74 Improve controller logic + fix tests flakiness
  README.md
  api/v1alpha1/extendeddaemonset_types.go
  api/v1alpha1/extendeddaemonsetreplicaset_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.openapi.go
  config/crd/bases/v1/datadoghq.com_extendeddaemonsets.yaml
  config/crd/bases/v1beta1/datadoghq.com_extendeddaemonsets.yaml
  controllers/extendeddaemonset/conditions/update.go
  controllers/extendeddaemonset/controller.go
  controllers/extendeddaemonset/controller_test.go
  controllers/extendeddaemonset/metrics.go
  controllers/extendeddaemonset/utils.go
  controllers/extendeddaemonset/utils_test.go
  controllers/extendeddaemonset_e2e_test.go
  controllers/extendeddaemonset_test.go
  controllers/extendeddaemonsetreplicaset/conditions/update.go
  controllers/extendeddaemonsetreplicaset/controller.go
  controllers/extendeddaemonsetreplicaset/strategy/canary.go
  controllers/extendeddaemonsetreplicaset/strategy/canary_test.go
  controllers/extendeddaemonsetreplicaset/strategy/limits/limits.go
  controllers/extendeddaemonsetreplicaset/strategy/limits/limits_test.go
  controllers/extendeddaemonsetreplicaset/strategy/rollingupdate.go
  controllers/extendeddaemonsetreplicaset/strategy/utils.go
  controllers/extendeddaemonsetreplicaset/strategy/utils_test.go
  controllers/suite_helpers_test.go
  controllers/testutils/update.go
  docs/canary-worflows.md
  pkg/plugin/canary/canary.go
  pkg/plugin/canary/fail.go
  pkg/plugin/canary/pause.go
  pkg/plugin/canary/validate.go
  pkg/plugin/get/get.go
  pkg/plugin/get/geters.go
  pkg/plugin/pods/pods.go
Labels: bug

#77 persist manual unpause until end of a canary deployment, and then reset
  api/v1alpha1/const.go
  controllers/extendeddaemonset/controller.go
  controllers/extendeddaemonset/controller_test.go
  controllers/extendeddaemonset/utils.go
  controllers/extendeddaemonset_e2e_test.go
  controllers/extendeddaemonsetreplicaset/strategy/canary.go
  controllers/extendeddaemonsetreplicaset/strategy/type.go
  examples/foo-eds_v1.yaml
  pkg/plugin/canary/fail.go
  pkg/plugin/canary/pause.go
Labels: enhancement

#79 Cherry-pick #77 on v0.5 release branch
  api/v1alpha1/const.go
  controllers/extendeddaemonset/controller.go
  controllers/extendeddaemonset/controller_test.go
  controllers/extendeddaemonset/utils.go
  controllers/extendeddaemonset_e2e_test.go
  controllers/extendeddaemonsetreplicaset/strategy/canary.go
  controllers/extendeddaemonsetreplicaset/strategy/type.go
  examples/foo-eds_v1.yaml
  pkg/plugin/canary/fail.go
  pkg/plugin/canary/pause.go
Labels: bug
