Repository DataDog/extendeddaemonset, pull requests merged in 2021-04, with the labels that each got.

#84 Support pausing and freezing non-canary replicasets
  api/v1alpha1/const.go
  api/v1alpha1/extendeddaemonset_types.go
  api/v1alpha1/extendeddaemonsetreplicaset_types.go
  config/rbac/leader_election_role.yaml
  controllers/extendeddaemonset/controller.go
  controllers/extendeddaemonset/controller_test.go
  controllers/extendeddaemonset/metrics.go
  controllers/extendeddaemonset/utils.go
  controllers/extendeddaemonset_e2e_test.go
  controllers/extendeddaemonset_test.go
  controllers/extendeddaemonsetreplicaset/controller.go
  controllers/extendeddaemonsetreplicaset/strategy/rollingupdate.go
  controllers/extendeddaemonsetreplicaset/strategy/type.go
  controllers/suite_helpers_test.go
  pkg/plugin/extendeddaemonset.go
  pkg/plugin/freeze/doc.go
  pkg/plugin/freeze/rollout.go
  pkg/plugin/pause/doc.go
  pkg/plugin/pause/rollingupdate.go
Labels: component/controller, component/plugin, enhancement

#85 Add ARM support and internal image
  .gitlab-ci.yml
  Dockerfile
  Makefile
  check-eds.Dockerfile
Labels: enhancement

#86 Fix how EDS is using the kube-scheduler when possible
  controllers/extendeddaemonset_test.go
  controllers/extendeddaemonsetreplicaset/filters.go
  pkg/controller/utils/pod/create.go
  pkg/controller/utils/pod/pod.go
Labels: bug, component/controller

#87 rename default branch to main
  README.md
  RELEASING.md
Labels: enhancement

#88 Delete failed pods with a backoff
  controllers/extendeddaemonsetreplicaset/controller.go
  controllers/extendeddaemonsetreplicaset/controller_test.go
  controllers/extendeddaemonsetreplicaset/filters.go
  controllers/extendeddaemonsetreplicaset/filters_test.go
Labels: enhancement

#89 Add telemetry to detect stuck rolling updates
  controllers/extendeddaemonset/controller.go
  controllers/extendeddaemonsetreplicaset/strategy/rollingupdate.go
  pkg/controller/metrics/custom_metrics.go
  pkg/controller/metrics/ksmetrics.go
  pkg/controller/utils/labels.go
Labels: component/controller, enhancement

#90 [ers scheduler] improve test coverage
  controllers/extendeddaemonsetreplicaset/scheduler/predicates_test.go
  pkg/controller/test/new.go
Labels: enhancement

#91 Fix leader election compatibility with old k8s version
  main.go
Labels: bug, component/controller

#93 Fix some help messages in the EDS plugin
  pkg/plugin/canary/fail.go
  pkg/plugin/canary/validate.go
  pkg/plugin/extendeddaemonset.go
Labels: documentation

#94 Fix EDS.status current pods
  .gitlab-ci.yml
  controllers/extendeddaemonset/controller.go
  pkg/plugin/canary/fail.go
  pkg/plugin/canary/validate.go
  pkg/plugin/extendeddaemonset.go
Labels: bug
