Repository DataDog/extendeddaemonset, pull requests merged in 2025-09, with the labels that each got.

#221 [v0.11] More fixes from main
  config/rbac/role.yaml
  controllers/extendeddaemonset_controller.go
  controllers/podtemplate_controller.go
  main.go
  pkg/config/config.go
  pkg/controller/debug/register.go
Labels: enhancement

#222 [tooling] Update pr linter job
  .github/workflows/pr-linter.yml
Labels: tooling, qa/skip-qa

#227 Release v0.11.0 rc.4
  .gitlab-ci.yml
  bundle/manifests/extendeddaemonset.clusterserviceversion.yaml
Labels: enhancement, qa/skip-qa
